version: '3.9'
services:
  mysql_bd:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: minha_senha_root
      MYSQL_DATABASE: distribuicao_db
    ports:
      - '3306:3306'
    volumes:
      - ./db_data:/var/lib/mysql
volumes:
  db_data: